  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_front_wheel_state_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_front_wheel_joint
    pid: {p: 1.0, i: 0.1, d: 0.1, i_clamp: 100}
  left_back_wheel_state_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_back_wheel_joint
    pid: {p: 1.0, i: 0.1, d: 0.1, i_clamp: 100}
  right_front_wheel_state_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_front_wheel_joint
    pid: {p: 1.0, i: 0.1, d: 0.1, i_clamp: 100}
  right_back_wheel_state_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_back_wheel_joint
    pid: {p: 1.0, i: 0.1, d: 0.1, i_clamp: 100}

  mobile_base_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: [left_front_wheel_joint, left_back_wheel_joint]
    right_wheel: [right_front_wheel_joint, right_back_wheel_joint]
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    wheel_separation: 0.5
    wheel_radius: 0.1

    base_frame_id: base_link

    enable_odom_tf: false
    publish_cmd: True
    allow_multiple_cmd_vel_publishers: True

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 2.
        min_velocity: -0.5

        has_acceleration_limits: true
        max_acceleration: 2.
        min_acceleration: -2.

        has_jerk_limits: false
        # max_jerk: 5.
      angular:
        z:
          has_velocity_limits: true
          max_velocity: 1.

          has_acceleration_limits: true
          max_acceleration: 2.5

          has_jerk_limits: false
          # max_jerk: 2.5
